version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Toor1234
      POSTGRES_DB: db_sales
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/data/postgres

volumes:
  postgres-vol: